--liquibase formatted sql

-- changeset GlakovaA:1
CREATE TABLE IF NOT EXISTS client_registration
(
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id                 BIGINT  NOT NULL,
    name                    TEXT NOT NULL,
    please_of_residence     TEXT NOT NULL,
    mobile_number           TEXT NOT NULL
);
-- changeset GlakovaA:2
CREATE TABLE volunteers
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        TEXT NOT NULL,
    please_of_residence     TEXT NOT NULL

);

-- changeset GlakovaA:3
CREATE INDEX client_registration_name_index ON volunteers (name);

-- changeset GlakovaA:4
ALTER TABLE client_registration add column volunteer_id  BIGINT REFERENCES volunteers (id);

-- changeset GlakovaA:5
CREATE TABLE report
(
    id                              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    picture                         VARCHAR NOT NULL,
    diet                            TEXT NOT NULL,
    well_being_and_addiction        TEXT NOT NULL,
    changeInBehavior                TEXT NOT NULL

);
