--liquibase formatted sql

-- changeset GlakovaA:1
CREATE TABLE IF NOT EXISTS client_registration
(
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id                 BIGINT  NOT NULL,
    name                    TEXT NOT NULL,
    please_of_residence     TEXT NOT NULL,
    mobile_number           TEXT NOT NULL
);
-- changeset GlakovaA:2
CREATE TABLE volunteers
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        TEXT NOT NULL,
    please_of_residence     TEXT NOT NULL

);

-- changeset GlakovaA:3
CREATE INDEX client_registration_name_index ON volunteers (name);

-- changeset GlakovaA:4
ALTER TABLE client_registration add column volunteer_id  BIGINT REFERENCES volunteers (id);

-- changeset GlakovaA:5
CREATE TABLE report
(
    id                              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    picture                         VARCHAR NOT NULL,
    diet                            TEXT NOT NULL,
    well_being_and_addiction        TEXT NOT NULL,
    changeInBehavior                TEXT NOT NULL
 );

-- changeset AlexSnegireff:6
CREATE TABLE users
(
    chat_id BIGINT PRIMARY KEY ,
    user_name TEXT,
    mobile_number TEXT,
    last_command TEXT,
    volunteer_trigger BOOLEAN
);
-- changeset GlakovaA:7
DROP TABLE client_registration

-- changeset GlakovaA:8
DROP TABLE volunteers

-- changeset GlakovaA:9
CREATE TABLE users_for_cat
(
    chat_id                     BIGINT PRIMARY KEY,
    user_name                   TEXT,
    mobile_number               TEXT,
    last_command                TEXT,
    volunteer_trigger_cat       BOOLEAN

);

-- changeset GlakovaA:10
CREATE TABLE volunteers
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chat_id          BIGINT,
    name             TEXT,
    last_command     TEXT
);

-- changeset GlakovaA:11
DROP TABLE report

-- changeset GlakovaA:12
CREATE TABLE report
(
    id                              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    picture                         BYTEA NOT NULL,
    diet                            TEXT NOT NULL,
    well_being_and_addiction        TEXT NOT NULL,
    change_in_behavior              TEXT NOT NULL

);





